# Generated by Django 4.2.4 on 2023-08-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine_reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Recto',
            new_name='recto',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Verso',
            new_name='verso',
        ),
    ]
