# Generated by Django 4.2.4 on 2023-08-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_reader', '0002_rename_recto_image_recto_rename_verso_image_verso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='recto',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
