# Generated by Django 4.2.4 on 2023-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_reader', '0003_remove_image_recto_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='recto',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='verso',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
    ]
