# Generated by Django 4.2.4 on 2023-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_reader', '0004_remove_image_name_image_recto_alter_image_verso'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
