# Generated by Django 4.2.4 on 2023-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_reader', '0006_remove_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rot',
            field=models.IntegerField(null=True),
        ),
    ]
