# Generated by Django 4.2.4 on 2023-08-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_reader', '0007_image_rot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
