# Generated by Django 4.2.4 on 2023-08-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_reader', '0008_alter_image_rot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rot',
            field=models.CharField(default='0,0', max_length=100, null=True),
        ),
    ]
